# Generated by Django 5.2.5 on 2025-09-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descroption',
            new_name='description',
        ),
    ]
