# Generated by Django 5.2.5 on 2025-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
