# Generated by Django 5.2.5 on 2025-10-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_category_is_fake_product_is_fake_subcategory_is_fake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_fake',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='is_fake',
        ),
    ]
