# Generated by Django 5.2.5 on 2025-10-21 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0013_remove_category_is_fake_remove_subcategory_is_fake'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=6)),
                ('extrainfo', models.TextField()),
                ('is_paid', models.BooleanField(default=False)),
                ('delivery_date', models.DateTimeField()),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=3)),
                ('authority', models.CharField(max_length=70)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('order',),
                'verbose_name_plural': 'orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_at', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.SmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pname', to='home.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
        ),
    ]
