# Generated by Django 5.2.5 on 2025-10-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='totalprice',
        ),
    ]
