# Generated by Django 5.2.5 on 2025-10-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_totalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='extrainfo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
