# Generated by Django 5.2.5 on 2025-10-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_extrainfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deliverd',
            field=models.BooleanField(default=False),
        ),
    ]
